### ISSUE TITLE
Update Days on homepage

### ISSUE THREAD

**Issue by cgrusden** [amberaultman/100daysofcode#1]
Read through the code on your index.html.haml page, and it only goes up to Day 3, but your latest commit says Day 7? Need to update the index with all the days so we can keep up with what you're working on :)

**Comment by amberaultman** [comment]
Hey! Yeah, that's a really good idea. I kept going back and forth on whether each day should be represented by a blog-like post or just by updates to the site. But I think you're right; I think it makes more sense to document what I did as a post. Stay tuned!
